### ISSUE TITLE
Swimming speed

### ISSUE THREAD

**Issue by Marsu-u** [ToCraft/woodwalkers-mod#179]
### Describe your idea, include images if necessary

In the 1,21,1 Version the swimming speed was much faster than itit is currently. Frogs or Dolphins would swim much faster than a player would and depth strider 3 would enhance the speed. 
Im currently playing in a 1.21.5 server with my friends and we are playing with the mod. I choosed a frog since I thought that it would swim fast but it didnt and the flying mobs such as a bat for example would fly as fast as they used to.  So I want to ask you if you could change that and bring back the old swimming speed since that would made the swimming mobs better and the flying mobs less unfair. Or can you tell me how I can enhance the swimming speed myself so that Im back to the old speed. Otherwise is the mod pretty fun thanks .

**Comment by Marsu-u** [comment]
Im talking about the woodwalkers/remorphed mod. Mainly woodwalkers though

**Comment by ToCraft** [comment]
fixed as of f462f9a606196094f44abebf6f14ac958ae32695

**Comment by Marsu-u** [comment]
Thanks you for responding but is this feature out yet ? because I use the newest version of the mod and the swimming speed is still the same in 1.21.5


> fixed as of [f462f9a](https://github.com/ToCraft/woodwalkers-mod/commit/f462f9a606196094f44abebf6f14ac958ae32695)

**Comment by ToCraft** [comment]
It will be available with the next update. I plan to publish it in approximately two weeks.
